-- ==================================================
-- Supabase RLS (Row Level Security) Disable Patch
-- Run this in Supabase SQL Editor to allow anonymous read/write access.
-- ==================================================

ALTER TABLE departments DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE vendors DISABLE ROW LEVEL SECURITY;
ALTER TABLE permissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE customer_contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE customer_sites DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE consumables DISABLE ROW LEVEL SECURITY;
ALTER TABLE consumable_purchase_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE consumable_purchase_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE consumable_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE contracts DISABLE ROW LEVEL SECURITY;
ALTER TABLE contract_assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE contract_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE deliveries DISABLE ROW LEVEL SECURITY;
ALTER TABLE billings DISABLE ROW LEVEL SECURITY;
ALTER TABLE billing_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_billings DISABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_billing_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE repairs DISABLE ROW LEVEL SECURITY;
ALTER TABLE repair_consumables DISABLE ROW LEVEL SECURITY;
ALTER TABLE announcements DISABLE ROW LEVEL SECURITY;
ALTER TABLE announcement_reads DISABLE ROW LEVEL SECURITY;
ALTER TABLE work_instructions DISABLE ROW LEVEL SECURITY;
ALTER TABLE collaboration_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE collaboration_request_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE bank_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE bank_matching_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE asset_inout_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE consumable_purchases DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE transport_drivers DISABLE ROW LEVEL SECURITY;
ALTER TABLE todos DISABLE ROW LEVEL SECURITY;
ALTER TABLE google_configs DISABLE ROW LEVEL SECURITY;
ALTER TABLE cash_flow_snapshots DISABLE ROW LEVEL SECURITY;
